version: '3'
services:
   nginx:
      image: nginx:latest
      container_name: nginx
      ports:
         - "80:80"
      restart: always
      volumes:
         - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      extra_hosts:
         - "wordpress:172.16.83.3"
      networks:
         app_net:
           ipv4_address: 172.16.88.2
   php:
      image: themiddle/php_cve-2019-11043
      container_name: php
      volumes:
         - ./php:/var/www/html
      networks:
         app_net:
           ipv4_address: 172.16.88.3
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.88.0/24
